### ISSUE TITLE
ncpfs for Kernel 5.6 got a system call error

### ISSUE THREAD

**Issue by jamiroquai27** [EnzephaloN/ncpfs-module#10]
Hello, 

i want use the kernel module for a debian 11 (5.10.0-27-amd64). I use the branch for 5.6. 
It compiles perfectly and the module was installed correctly too. 

But if i want mount a novell file share, i've got an error message:

**"mount(2) system call failed: Channel number out of range"**

Is there any known reason for this?

Thx a lot for this project. 

Best regards,
Andreas

**Comment by EnzephaloN** [comment]
Hi there.
I think I saw such error in the past. But I do not remember about it in detail.
Could you solve this?

best regards

**Comment by jamiroquai27** [comment]
Hello, 

yes i think so... our NCP protcol version lower than three, so we can't use the module for our purpose.

best regards
Andreas
