### ISSUE TITLE
No compilling...

### ISSUE THREAD

**Issue by serfcity** [EnzephaloN/ncpfs-module#5]
Hello.
I try compile this module, but I have a lot of errors:
`make -C /lib/modules/5.10.0-8-amd64/build M=/home/leonid/ncpfs-module modules
make[1]: вход в каталог «/usr/src/linux-headers-5.10.0-8-amd64»
  CC [M]  /home/leonid/ncpfs-module/dir.o
In file included from /home/leonid/ncpfs-module/ncp_fs.h:102,
                 from /home/leonid/ncpfs-module/dir.c:25:
/home/leonid/ncpfs-module/ncplib_kernel.h:189:2: error: unknown type name ‘time_t’
  189 |  time_t  mtime;
      |  ^~~~~~
/home/leonid/ncpfs-module/dir.c:62:13: error: initialization of ‘int (*)(struct inode *, struct dentry *, umode_t,  bool)’ {aka ‘int (*)(struct inode *, struct dentry *, short unsigned int,  _Bool)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t,  bool)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int,  _Bool)’} [-Werror=incompatible-pointer-types]
   62 |  .create  = ncp_create,
      |             ^~~~~~~~~~
/home/leonid/ncpfs-module/dir.c:62:13: note: (near initialization for ‘ncp_dir_inode_operations.create’)
/home/leonid/ncpfs-module/dir.c:65:13: error: initialization of ‘int (*)(struct inode *, struct dentry *, const char *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, const char *)’ [-Werror=incompatible-pointer-types]
   65 |  .symlink = ncp_symlink,
      |             ^~~~~~~~~~~
/home/leonid/ncpfs-module/dir.c:65:13: note: (near initialization for ‘ncp_dir_inode_operations.symlink’)
/home/leonid/ncpfs-module/dir.c:66:12: error: initialization of ‘int (*)(struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct inode *, struct dentry *, short unsigned int)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int)’} [-Werror=incompatible-pointer-types]
   66 |  .mkdir  = ncp_mkdir,
      |            ^~~~~~~~~
/home/leonid/ncpfs-module/dir.c:66:12: note: (near initialization for ‘ncp_dir_inode_operations.mkdir’)
/home/leonid/ncpfs-module/dir.c:68:12: error: initialization of ‘int (*)(struct inode *, struct dentry *, umode_t,  dev_t)’ {aka ‘int (*)(struct inode *, struct dentry *, short unsigned int,  unsigned int)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t,  dev_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int,  unsigned int)’} [-Werror=incompatible-pointer-types]
   68 |  .mknod  = ncp_mknod,
      |            ^~~~~~~~~
/home/leonid/ncpfs-module/dir.c:68:12: note: (near initialization for ‘ncp_dir_inode_operations.mknod’)
/home/leonid/ncpfs-module/dir.c:69:13: error: initialization of ‘int (*)(struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)’ [-Werror=incompatible-pointer-types]
   69 |  .rename  = ncp_rename,
      |             ^~~~~~~~~~
/home/leonid/ncpfs-module/dir.c:69:13: note: (near initialization for ‘ncp_dir_inode_operations.rename’)
/home/leonid/ncpfs-module/dir.c:70:13: error: initialization of ‘int (*)(struct dentry *, struct iattr *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct dentry *, struct iattr *)’ [-Werror=incompatible-pointer-types]
   70 |  .setattr = ncp_notify_change,
      |             ^~~~~~~~~~~~~~~~~
/home/leonid/ncpfs-module/dir.c:70:13: note: (near initialization for ‘ncp_dir_inode_operations.setattr’)
/home/leonid/ncpfs-module/dir.c:407:8: error: unknown type name ‘time_t’
  407 | static time_t ncp_obtain_mtime(struct dentry *dentry)
      |        ^~~~~~
/home/leonid/ncpfs-module/dir.c: In function ‘ncp_readdir’:
/home/leonid/ncpfs-module/dir.c:445:2: error: unknown type name ‘time_t’; did you mean ‘ktime_t’?
  445 |  time_t mtime = 0;
      |  ^~~~~~
      |  ktime_t
`
How to fix it?
Thank you.

**Comment by EnzephaloN** [comment]
Please read the documentation - you are using the wrong branch. Please use https://github.com/EnzephaloN/ncpfs-module/tree/kernel_5.6
