### ISSUE TITLE
Problem with make on linuxmint 21.1 (linux as of 15 march 2023)

### ISSUE THREAD

**Issue by riwide** [EnzephaloN/ncpfs-module#6]
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-67-generic'
  CC [M]  /home/rwdeane/ncpfs-module/dir.o
  CC [M]  /home/rwdeane/ncpfs-module/file.o
  CC [M]  /home/rwdeane/ncpfs-module/inode.o
  CC [M]  /home/rwdeane/ncpfs-module/ioctl.o
  CC [M]  /home/rwdeane/ncpfs-module/mmap.o
  CC [M]  /home/rwdeane/ncpfs-module/ncplib_kernel.o
  CC [M]  /home/rwdeane/ncpfs-module/sock.o
  CC [M]  /home/rwdeane/ncpfs-module/ncpsign_kernel.o
  CC [M]  /home/rwdeane/ncpfs-module/getopt.o
  CC [M]  /home/rwdeane/ncpfs-module/symlink.o
/home/rwdeane/ncpfs-module/symlink.c:44:61: warning: ‘struct folio’ declared inside parameter list will not be visible outside of this definition or declaration
   44 | static int ncp_symlink_read_folio(struct file *file, struct folio *folio)
      |                                                             ^~~~~
/home/rwdeane/ncpfs-module/symlink.c: In function ‘ncp_symlink_read_folio’:
/home/rwdeane/ncpfs-module/symlink.c:46:36: error: invalid use of undefined type ‘struct folio’
   46 |         struct inode *inode = folio->mapping->host;
      |                                    ^~

**Comment by EnzephaloN** [comment]
Hello

Like the documentations describes, you have to switch to the correct branch! In your case https://github.com/EnzephaloN/ncpfs-module/tree/kernel_5.15 .

**Comment by riwide** [comment]
Thank you for your response. I am a novice at this. Trying to get novell
multiuser dos networking to novell server under Linux and wanted to get
Linux connecting to netware server.

Cheers
Richard

**Comment by EnzephaloN** [comment]
You should have to know how to use git and some other basics, if you want to compile a piece of software ;-) . Switching to another branch is necessary here.

````
git clone https://github.com/EnzephaloN/ncpfs-module.git
cd ncpfs-module
git checkout kernel_5.15
make
sudo make install
sudo modprobe ncpfs
sudo lsmod | grep ncpfs
````
This should work for your system.

But, you also need the ncpfs-utils (like ncpmount, ncplogin, etc.), which are not part of this project.

**Comment by riwide** [comment]
Thanks, been using git and make, just did not realise I had to checkout the
specific branch. Shall give that a go.

I am retired now but back in the day, DRDOS, Multiuser DOS and Personal
NetWare were my babies when I worked as Software Test Manager at Digital
Research , European Development  Centre in Hungerford, UK.

Cheers
Richard
