### ISSUE TITLE
Kernel 6.3.1 incompatible

### ISSUE THREAD

**Issue by geosone** [EnzephaloN/ncpfs-module#7]
` * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found sources for kernel version:
 *     6.3.1-xanmod1-dist
 * Checking for suitable kernel configuration options ...                                                                                                                                                  [ ok ]
>>> Unpacking source...
 * Repository id: EnzephaloN_ncpfs-module.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_ENZEPHALON_NCPFS_MODULE
 *   EGIT_OVERRIDE_BRANCH_ENZEPHALON_NCPFS_MODULE
 *   EGIT_OVERRIDE_COMMIT_ENZEPHALON_NCPFS_MODULE
 *   EGIT_OVERRIDE_COMMIT_DATE_ENZEPHALON_NCPFS_MODULE
 * 
 * Fetching https://github.com/EnzephaloN/ncpfs-module.git ...
git fetch https://github.com/EnzephaloN/ncpfs-module.git +refs/heads/master:refs/heads/master
git symbolic-ref refs/git-r3/net-fs/ncpfs-modules/0/__main__ refs/heads/master
 * Checking out https://github.com/EnzephaloN/ncpfs-module.git to /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999 ...
git checkout --quiet master
GIT update -->
   repository:               https://github.com/EnzephaloN/ncpfs-module.git
   at the commit:            3fe5fe2ceb1e5d4175ce32f9afe388bd2d94e8ef
>>> Source unpacked in /var/tmp/portage/net-fs/ncpfs-modules-9999/work
>>> Preparing source in /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999 ...
ln: failed to create symbolic link 'Module.symvers': File exists
 * Preparing ncpfs module
make -j12 -s HOSTCC=x86_64-pc-linux-gnu-gcc 'LDFLAGS=-m elf_x86_64' KDIR=/usr/src/linux M=/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999 all 
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/ioctl.c: In function ‘ncp_ioctl’:
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/ioctl.c:877:48: error: passing argument 1 of ‘inode_permission’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  877 |                         ret = inode_permission(&init_user_ns, inode, MAY_WRITE);
      |                                                ^~~~~~~~~~~~~
      |                                                |
      |                                                struct user_namespace *
In file included from ./include/linux/compat.h:17,
                 from /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/ioctl.c:12:
./include/linux/fs.h:2476:22: note: expected ‘struct mnt_idmap *’ but argument is of type ‘struct user_namespace *’
 2476 | int inode_permission(struct mnt_idmap *, struct inode *, int);
      |                      ^~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/ioctl.c:889:48: error: passing argument 1 of ‘inode_permission’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  889 |                         ret = inode_permission(&init_user_ns, inode, MAY_WRITE);
      |                                                ^~~~~~~~~~~~~
      |                                                |
      |                                                struct user_namespace *
./include/linux/fs.h:2476:22: note: expected ‘struct mnt_idmap *’ but argument is of type ‘struct user_namespace *’
 2476 | int inode_permission(struct mnt_idmap *, struct inode *, int);
      |                      ^~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:62:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, umode_t,  bool)’ {aka ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, short unsigned int,  _Bool)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t,  bool)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int,  _Bool)’} [-Werror=incompatible-pointer-types]
   62 |         .create         = ncp_create,
      |                           ^~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:62:27: note: (near initialization for ‘ncp_dir_inode_operations.create’)
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:65:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, const char *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, const char *)’ [-Werror=incompatible-pointer-types]
   65 |         .symlink        = ncp_symlink,
      |                           ^~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:65:27: note: (near initialization for ‘ncp_dir_inode_operations.symlink’)
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:66:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, short unsigned int)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int)’} [-Werror=incompatible-pointer-types]
   66 |         .mkdir          = ncp_mkdir,
      |                           ^~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:66:27: note: (near initialization for ‘ncp_dir_inode_operations.mkdir’)
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:68:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, umode_t,  dev_t)’ {aka ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, short unsigned int,  unsigned int)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t,  dev_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int,  unsigned int)’} [-Werror=incompatible-pointer-types]
   68 |         .mknod          = ncp_mknod,
      |                           ^~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:68:27: note: (near initialization for ‘ncp_dir_inode_operations.mknod’)
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:69:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)’ [-Werror=incompatible-pointer-types]
   69 |         .rename         = ncp_rename,
      |                           ^~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:69:27: note: (near initialization for ‘ncp_dir_inode_operations.rename’)
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:70:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct dentry *, struct iattr *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct dentry *, struct iattr *)’ [-Werror=incompatible-pointer-types]
   70 |         .setattr        = ncp_notify_change,
      |                           ^~~~~~~~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.c:70:27: note: (near initialization for ‘ncp_dir_inode_operations.setattr’)
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/file.c:262:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct dentry *, struct iattr *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct dentry *, struct iattr *)’ [-Werror=incompatible-pointer-types]
  262 |         .setattr        = ncp_notify_change,
      |                           ^~~~~~~~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/file.c:262:27: note: (near initialization for ‘ncp_file_inode_operations.setattr’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/file.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.c:250:27: error: initialization of ‘int (*)(struct mnt_idmap *, struct dentry *, struct iattr *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct dentry *, struct iattr *)’ [-Werror=incompatible-pointer-types]
  250 |         .setattr        = ncp_notify_change,
      |                           ^~~~~~~~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.c:250:27: note: (near initialization for ‘ncp_symlink_inode_operations.setattr’)
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.c: In function ‘ncp_notify_change’:
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.c:883:34: error: passing argument 1 of ‘setattr_prepare’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  883 |         result = setattr_prepare(mnt_userns, dentry, attr);
      |                                  ^~~~~~~~~~
      |                                  |
      |                                  struct user_namespace *
In file included from ./include/linux/huge_mm.h:8,
                 from ./include/linux/mm.h:855,
                 from /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.c:21:
./include/linux/fs.h:2947:21: note: expected ‘struct mnt_idmap *’ but argument is of type ‘struct user_namespace *’
 2947 | int setattr_prepare(struct mnt_idmap *, struct dentry *, struct iattr *);
      |                     ^~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.c:945:46: error: passing argument 1 of ‘setattr_copy’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  945 |                                 setattr_copy(mnt_userns, inode, &tmpattr);
      |                                              ^~~~~~~~~~
      |                                              |
      |                                              struct user_namespace *
./include/linux/fs.h:2949:19: note: expected ‘struct mnt_idmap *’ but argument is of type ‘struct user_namespace *’
 2949 | void setattr_copy(struct mnt_idmap *, struct inode *inode,
      |                   ^~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.c:1017:22: error: passing argument 1 of ‘setattr_copy’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1017 |         setattr_copy(mnt_userns, inode, attr);
      |                      ^~~~~~~~~~
      |                      |
      |                      struct user_namespace *
./include/linux/fs.h:2949:19: note: expected ‘struct mnt_idmap *’ but argument is of type ‘struct user_namespace *’
 2949 | void setattr_copy(struct mnt_idmap *, struct inode *inode,
      |                   ^~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/ioctl.o] Error 1
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/inode.o] Error 1
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999/dir.o] Error 1
make[1]: *** [Makefile:2180: /var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999] Error 2
make: *** [Makefile:49: all] Error 2
 * ERROR: net-fs/ncpfs-modules-9999::linamh failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-fs/ncpfs-modules-9999::linamh'`,
 * the complete build log and the output of `emerge -pqv '=net-fs/ncpfs-modules-9999::linamh'`.
 * The complete build log is located at '/var/tmp/portage/net-fs/ncpfs-modules-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-fs/ncpfs-modules-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999'
 * S: '/var/tmp/portage/net-fs/ncpfs-modules-9999/work/ncpfs-modules-9999'

>>> Failed to emerge net-fs/ncpfs-modules-9999, Log file:
`

**Comment by geosone** [comment]
could you have a look into it ?

**Comment by EnzephaloN** [comment]
> could you have a look into it ?

we're testing our patch.

**Comment by EnzephaloN** [comment]
Please try our new master. If it works - close this ticket.

**Comment by geosone** [comment]
it is compiling will test next week with netware 5.1 & thanks
